### ISSUE TITLE
TODO： Wayland Protocols

### ISSUE THREAD

**Issue by wineee** [vioken/waylib#288]
### necessary

- [x] https://wayland.app/protocols/wlr-screencopy-unstable-v1
- [x] https://wayland.app/protocols/xdg-output-unstable-v1
- [x] https://github.com/vioken/waylib/issues/188
- [x] https://github.com/vioken/waylib/issues/175 
- [x] [ext-idle-notify-v1](https://wayland.app/protocols/ext-idle-notify-v1) https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3753

### low priority

- [x] https://wayland.app/protocols/wlr-data-control-unstable-v1
- [x] https://wayland.app/protocols/wlr-output-power-management-unstable-v1
- [ ] https://wayland.app/protocols/wlr-input-inhibitor-unstable-v1
- [ ] https://wayland.app/protocols/xwayland-keyboard-grab-unstable-v1
- [ ] https://wayland.app/protocols/xdg-foreign-unstable-v2
- [ ] https://wayland.app/protocols/ext-session-lock-v1
- [ ] https://wayland.app/protocols/content-type-v1
- [ ] https://wayland.app/protocols/tearing-control-v1 

### Waiting for upstream

- https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/28
- [ ] https://wayland.app/protocols/xdg-toplevel-drag-v1 
- [ ] https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/228
